amp: true
auto_augment: false
batch: 8
copy_paste: 0.5724015565785052
copy_paste_mode: flip
cos_lr: true
degrees: 10.643922473493117
dfl: 1.1048464720810045
dropout: 0.4020579102884976
#ema_decay_leftover: 0.003287126596792849
#ema_tau:  200
epochs: 100
fliplr: 0.5
flipud: 0.5
hsv_h: 0.14279391195559032
hsv_s: 0.8786257439361446
hsv_v: 0.5253497344285151
imgsz: 1280
lr0: 0.0003557350706650609
mixup: 0.3385200180981422
model: yolo11m
mosaic: 0.640896386418819
nbs: 64
optimizer: AdamW
patience: 10
perspective: 0.00010259018556426804
plots: true
scale: 0.011977278069699736
shear: 15.338620122849711
translate: 0.03
warmup_epochs: 6.195666315269232
weight_decay: 5.701297989312746e-05
